var mongoose = require('mongoose');
var User = require('../models/user');

var databaseUri = require('../config/db')('development');
mongoose.connect(databaseUri);

User.collection.drop();

User.create([
  {
    username: "dave",
    email: "dave@mail",
    password: "password",
    passwordConfirmation: "password",
    age: 34,
    avatar:"no_image.png",
    locationNameHome: "Clapham",
    locationHome: {lat:51.4882, lng:-0.0193},
    locationNameWork: "Aldgate",
    locationWork: {lat:51.4995, lng:-0.1234},
    occupation:"Under cars fixing things",
    foodPreference: "25",
    drinkPreference: "67",
    filmPreference: "54",
    bookPreference: "45",
    entertainmentPreference: "66",
    meetCuisines:"Indian", 
    activeMeet: true,
    chatRoom:"room1",
    loggedIn: true,
    meetMeal: "lunch"
    },{
    username: "susan",
    email: "susan@mail",
    password: "password",
    passwordConfirmation: "password",
    avatar:"no_image.png",
    occupation:"Making cakes for sale",
    age: 45,
    locationNameHome: "Islington",
    locationHome: {lat:51.4000, lng:-0.1234},
    locationNameWork: "Moorgate",
    locationWork: {lat:51.5342, lng:-0.1005},
    foodPreference: "43",
    drinkPreference: "56",
    filmPreference: "73",
    bookPreference: "25",
    entertainmentPreference: "25",
    meetCuisines:"French", 
    activeMeet: true,
    chatRoom:"room1",
    meetMeal:"Breakfast"

  },{
    username: "eifion",
    email: "eifion@mail",
    password: "password",
    passwordConfirmation: "password",
    avatar:"no_image.png",
    occupation: "As a lawyer in the city",
    age: 44,
    locationNameHome: "Chelsea",
    locationHome: {lat:51.3456, lng:-0.1111},
    locationNameWork: "Old Street",
    locationWork: {lat:51.4005, lng:-0.1004},
    foodPreference: "87",
    drinkPreference: "85",
    filmPreference: "76",
    bookPreference: "66",
    entertainmentPreference: "66",
    meetCuisines:"British", 
    meetMeal:"Dinner",
    activeMeet: true
  },{
    username: "julian",
    email: "julian@mail",
    password: "password",
    passwordConfirmation: "password",
    avatar:"no_image.png",
    occupation: "Writing the code to make this site work",
    age: 33,
    locationNameHome: "Vauxhall",
    locationHome: {lat:51.3762, lng:-0.1393},
    locationNameWork: "Aldgate",
    locationWork: {lat:51.2235, lng:-0.1034},
    foodPreference: "55",
    drinkPreference: "67",
    filmPreference: "65",
    bookPreference: "89",
    entertainmentPreference: "66",
    meetCuisines:"Korean", 
    activeMeet: true,
    chatRoom:"room2",
    loggedIn: true,
    meetMeal: "Brunch"
  },{
    username: "sarah",
    email: "sarah@mail",
    password: "password",
    passwordConfirmation: "password",
    avatar:"no_image.png",
    occupation: "Arranging flowers formhotes",
    age: 28,
    locationNameHome: "Parsons Green",
    locationHome: {lat:51.356, lng:-0.1473},
    locationNameWork: "Aldgate",
    locationWork: {lat:51.2535, lng:-0.1534},
    foodPreference: "55",
    drinkPreference: "67",
    filmPreference: "65",
    bookPreference: "89",
    entertainmentPreference: "66",
    meetCuisines:"Mexican", 
    activeMeet: true,
    chatRoom:"room2",
    loggedIn: true,
    meetMeal:"Dinner"
  },  {
    username: "Mary",
    email: "mary@mail",
    password: "password",
    passwordConfirmation: "password",
    age: 27,
    avatar:"no_image.png",
    locationNameHome: "Northolt",
    locationHome: {lat:51.3333, lng:-0.1873},
    locationNameWork: "Hackney",
    locationWork: {lat:51.4005, lng:-0.1444},
    occupation:"Selling hats in HAckney",
    foodPreference: "25",
    drinkPreference: "67",
    filmPreference: "54",
    bookPreference: "45",
    entertainmentPreference: "66",
    meetCuisines:"Indian", 
    activeMeet: true,
    chatRoom:"room1",
    loggedIn: false,
    meetMeal:"Breakfast"
    },{
    username: "Gillian",
    email: "gillian@mail",
    password: "password",
    passwordConfirmation: "password",
    avatar:"no_image.png",
    occupation:"Working in a hospital as a nurse",
    age: 45,
    locationNameHome: "Islington",
    locationHome: {lat:51.4068, lng:-0.1769},
    locationNameWork: "Camberwell",
    locationWork: {lat:51.5342, lng:-0.1005},
    foodPreference: "43",
    drinkPreference: "56",
    filmPreference: "73",
    bookPreference: "25",
    entertainmentPreference: "25",
    meetCuisines:"French", 
    meetMeal:"Breakfast",
    activeMeet: true,
    chatRoom:"room1",
    loggedIn: false
  },{
    username: "Mike",
    email: "mike@mail",
    password: "password",
    passwordConfirmation: "password",
    avatar:"no_image.png",
    occupation: "Recovering from teaching at GA",
    age: 44,
    locationNameHome: "Shadwell",
    locationHome: {lat:51.3456, lng:-0.1111},
    locationNameWork: "Aldgate East",
    locationWork: {lat:51.4005, lng:-0.1004},
    foodPreference: "87",
    drinkPreference: "85",
    filmPreference: "76",
    bookPreference: "66",
    entertainmentPreference: "66",
    meetCuisines:"British", 
    meetMeal:"Dinner",
    activeMeet: true,
    loggedIn: false
  },{
    username: "Mark",
    email: "mark@mail",
    password: "password",
    passwordConfirmation: "password",
    avatar:"no_image.png",
    occupation: "Not much just want yo meet someone",
    age: 33,
    locationNameHome: "Vauxhall",
    locationHome: {lat:51.3762, lng:-0.1793},
    locationNameWork: "Peckham",
    locationWork: {lat:51.2235, lng:-0.1034},
    foodPreference: "55",
    drinkPreference: "45",
    filmPreference: "65",
    bookPreference: "77",
    entertainmentPreference: "66",
    meetCuisines:"Indian",
    activeMeet: true,
    chatRoom:"room2",
    meetMeal:"Lunch",
    loggedIn: true
  },{
    username: "Chanse",
    email: "chanse@mail",
    password: "password",
    passwordConfirmation: "password",
    avatar:"no_image.png",
    occupation: "Starting a new job next week",
    age: 28,
    locationNameHome: "Aldgate",
    locationHome: {lat:51.3555, lng:-0.1009},
    locationNameWork: "Ealing",
    locationWork: {lat:51.456, lng:-0.1594},
    foodPreference: "55",
    drinkPreference: "67",
    filmPreference: "65",
    bookPreference: "89",
    entertainmentPreference: "66",
    meetCuisines:"Mexican", 
    meetMeal:"Dinner",
    activeMeet: true,
    chatRoom:"room2",
    loggedIn: true
  }
], function(err, users) {
  console.log(users);
  mongoose.connection.close();
})